Web:
  WebHost: 0.0.0.0:5002
  IgnoreURLs:
    - /
    - /auth/login
    - /auth/verifycode

JWTCfg:
  JwtRenewSwitch: false
  JwtTimeOut: 86400 #second
  JwtLogLevel: debug
  JwtSecret: secret

Log:
  LogPath: ./
  LogLevel: info
  MaxSize: 50
  MaxAge: 7
  Stacktrace: error
  IsStdOut: yes

Mongodb:
  Host: 121.199.167.227
  Port: 27017
  User: sun
  Passwd: sun#sun
  DbName: db_sun

Redis:
  RedisHost: 121.199.167.227:6379
  RedisPasswd: 123456
  SubChannel: route.srv

Tracking: